[package]
name = "ionize"
description = "Clone repos effortlessly"
version = "0.3.6"
authors = ["selfup <boudinot.regis@yahoo.com>"]
license = "MIT"
repository = "https://github.com/selfup/ionize"
readme = "README.md"

[dependencies]
