[package]
name = "ionize"
description = "Clone repos effortlessly"
version = "0.3.2"
authors = ["selfup <boudinot.regis@yahoo.com>"]
license = "MIT"
repository = "https://github.com/selfup/ionize"

[dependencies]
